var params = {
  font: 1.5,
  curve: 100,
  ampcurve:2,
  curveopacity:1,
  border:1,
  showtext: true,
  showcurve: true,
  visualize: "Both",
  curve_color: "#b0c4de",
  text_color: "#000000",
  n_avg: 1,
  zoomlvl: 1,
  panx: 50,
  pany: 50,
  showbold: false,
  boldval: 8,
  phrasespacing: 0.3,
  pltint:false,
  speed:15,
  subvizx: 0,
  subvizy: 1,
  links: links,
  num_files:0,
  num_words: 10,
  audio: " ",
  noisefloor:0.1,
  noise:false,
  norm:true,
  ofs:false,
  showvol:false,
  showpit:true,
  pltbinned:true,
  pltphrase:false,
  keepplaying:true,
  abstr:false,
  zoomon:false,
  gradient:true,
  height:3,
  width:1.5,
  showstats:false,
  cmap:false
  //bold_value: 1
};
